services:
  database:
    image: 'postgres:15-alpine'
    container_name: 'database'
    restart: 'always'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=db'
    volumes:
      - 'data:/var/lib/'
    ports:
      - '5432'




volumes:
  data: