services:
  database:
    image: 'postgres:15-alpine'
    container_name: 'database'
    restart: 'always'
    networks:
      - red
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=db'
    volumes:
      - 'data:/var/lib/'
    ports:
      - '5432'

  application:
    build:
      context: ./
      dockerfile: 'Dockerfile'
    container_name: 'application'
    restart: 'always'
    networks:
      - 'red'
    depends_on:
      - 'database'
    ports:
      - '2020:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db'
      - 'SPRING_DATASOURCE_USERNAME=db'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
      - 'SPRING.JPA.PROPERTIES.HIBERNATE.DIALECT=org.hibernate.dialect.PostgreSQLDialect'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
      - 'SPRING_JPA_SHOW=true'

volumes:
  'data':

networks:
  'red':